---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages and Java
  apt:
    name:
      - curl
      - gnupg
      - unzip
      - tar
      - ca-certificates
      - openjdk-17-jdk
    state: present
